
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- AUTOGENERATED HYPRLAND CONFIG.                        --
-- EDIT THIS CONFIG ACCORDING TO THE WIKI INSTRUCTIONS.  --
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --


-- This is an example Hyprland Lua config file.
-- Refer to the wiki for more information.
-- https://wiki.hypr.land/Configuring/Start/

-- Please note not all available settings / options are set here.
-- For a full list, see the wiki

-- You can (and should!!) split this configuration into multiple files
-- Create your files separately and then require them like this:
-- require("myColors")


------------------
---- MONITORS ----
------------------

-- See https://wiki.hypr.land/Configuring/Basics/Monitors/
hl.monitor({
    output   = "eDP-1",
    mode     = "1920x1200@60",
    position = "0x0",
    scale    = 1.0,
})

-- LG UltraGear, au-dessus du laptop
hl.monitor({
    output   = "HDMI-A-1",
    mode     = "2560x1440@143.93",
    position = "auto-up",
    scale    = 1.0,
})

-- Fallback for any monitor not explicitly declared above (e.g. plug in a
-- second screen before adding a dedicated rule for it) : au-dessus du laptop
-- par défaut aussi.
hl.monitor({
    output   = "",
    mode     = "preferred",
    position = "auto-up",
    scale    = "auto",
})


---------------------
---- MY PROGRAMS ----
---------------------

-- Set programs that you use
local terminal    = "kitty"
local fileManager = "nautilus --new-window" -- swap for thunar, dolphin, nemo...

-- Palette DA : ces deux lignes sont gérées par theme/generate.sh (voir
-- theme/palette.sh) — ne pas éditer directement, ce serait écrasé.
local themeAccent   = "e91e8c"
local themeFauxnoir = "1d2021"
local menu        = "rofi -show drun"


-------------------
---- AUTOSTART ----
-------------------

-- See https://wiki.hypr.land/Configuring/Basics/Autostart/

-- Autostart necessary processes (like notifications daemons, status bars, etc.)
-- Or execute your favorite apps at launch like this:
--
-- hl.on("hyprland.start", function ()
--   hl.exec_cmd(terminal)
--   hl.exec_cmd("nm-applet")
--   hl.exec_cmd("waybar & hyprpaper & firefox")
-- end)

hl.on("hyprland.start", function ()
    -- Propage les variables de session vers D-Bus/systemd --user : sans ça,
    -- les apps lancées via activation D-Bus/systemd (scopes systemd, comme
    -- VS Code) ne voient pas forcément XDG_CURRENT_DESKTOP même si Hyprland
    -- lui-même l'a — repéré en debuggant pourquoi VS Code ne détectait
    -- jamais gnome-keyring malgré un trousseau qui marchait très bien par
    -- ailleurs (testé avec Brave). Doit tourner avant tout le reste.
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP XDG_SESSION_DESKTOP DESKTOP_SESSION XDG_SESSION_TYPE HYPRLAND_INSTANCE_SIGNATURE DISPLAY SSH_AUTH_SOCK")
    hl.exec_cmd("systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP XDG_SESSION_DESKTOP DESKTOP_SESSION XDG_SESSION_TYPE HYPRLAND_INSTANCE_SIGNATURE DISPLAY SSH_AUTH_SOCK")

    -- Réveille fprintd dès la session plutôt que d'attendre le premier
    -- déverrouillage : il tourne en activation D-Bus à la demande et
    -- s'arrête après inactivité, or le redémarrer à froid déclenche un
    -- reset USB du capteur (voir systemd-overrides/fprintd.service.d/)
    -- qui n'a pas le temps de finir avant le prompt d'empreinte. Un appel
    -- D-Bus normal (via fprintd-list) déclenche l'activation sans les
    -- droits root qu'exigerait un "systemctl start" direct sur ce service
    -- système.
    hl.exec_cmd("fprintd-list \"$USER\" >/dev/null 2>&1")

    hl.exec_cmd("waybar")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("awww-daemon")
    hl.exec_cmd("sleep 1 && awww img $HOME/Pictures/wallpapers/gruvbox-tranquility.png")
    hl.exec_cmd("hyprsunset --temperature 3600")
    hl.exec_cmd("/usr/lib/polkit-kde-authentication-agent-1")
    hl.exec_cmd("swaync")
    -- Etat initial des indicateurs custom du buttons-grid swaync (voir
    -- .config/swaync/scripts/, contournement du bug amont #739)
    hl.exec_cmd("sleep 1 && $HOME/.config/swaync/scripts/update-bluetooth-state.sh")
    hl.exec_cmd("sleep 1 && $HOME/.config/swaync/scripts/update-airplane-state.sh")
    hl.exec_cmd("sleep 1 && $HOME/.config/swaync/scripts/update-powerprofile-state.sh")
end)


-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Environment-variables/

hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")

-- Thème Qt (qt6ct + palette Gruvbrutal) pour les rares apps Qt du bureau,
-- surtout polkit-kde-agent. Mirroir de .config/environment.d/50-qt-theme.conf
-- (qui couvre en plus les process activés par systemd/D-Bus).
hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")


-----------------------
----- PERMISSIONS -----
-----------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Permissions/
-- Please note permission changes here require a Hyprland restart and are not applied on-the-fly
-- for security reasons

-- hl.config({
--   ecosystem = {
--     enforce_permissions = true,
--   },
-- })

-- hl.permission("/usr/(bin|local/bin)/grim", "screencopy", "allow")
-- hl.permission("/usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland", "screencopy", "allow")
-- hl.permission("/usr/(bin|local/bin)/hyprpm", "plugin", "allow")


-----------------------
---- LOOK AND FEEL ----
-----------------------

-- Refer to https://wiki.hypr.land/Configuring/Basics/Variables/
hl.config({
    general = {
        -- Plus de marge en bas/droite/entre les fenêtres pour laisser respirer
        -- l'ombre portée neobrutalism (décalée vers le bas-droite)
        gaps_in  = { top = 4,  right = 10, bottom = 10, left = 4 },
        gaps_out = { top = 8,  right = 14, bottom = 14, left = 8 },

        border_size = 3,

        col = {
            active_border   = "rgba(" .. themeAccent .. "ee)",
            inactive_border = "rgba(" .. themeFauxnoir .. "aa)",
        },

        -- Set to true to enable resizing windows by clicking and dragging on borders and gaps
        resize_on_border = true,

        -- Please see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Tearing/ before you turn this on
        allow_tearing = false,

        layout = "dwindle",
    },

    decoration = {
        rounding       = 3,
        rounding_power = 2,

        -- Change transparency of focused and unfocused windows
        active_opacity   = 1.0,
        inactive_opacity = 1.0,

        -- Neobrutalism : ombre dure décalée en faux noir, pas de flou
        shadow = {
            enabled  = true,
            color    = "rgba(" .. themeFauxnoir .. "ff)",
            offset   = { 5, 5 },
            range    = 2,
            sharp    = true,
        },

        blur = {
            enabled   = true,
            size      = 3,
            passes    = 1,
            vibrancy  = 0.1696,
        },
    },

    animations = {
        enabled = true,
    },
})

-- Default curves and animations, see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Animations/
hl.curve("easeOutQuint",   { type = "bezier", points = { {0.23, 1},    {0.32, 1}    } })
hl.curve("easeInOutCubic", { type = "bezier", points = { {0.65, 0.05}, {0.36, 1}    } })
hl.curve("linear",         { type = "bezier", points = { {0, 0},       {1, 1}       } })
hl.curve("almostLinear",   { type = "bezier", points = { {0.5, 0.5},   {0.75, 1}    } })
hl.curve("quick",          { type = "bezier", points = { {0.15, 0},    {0.1, 1}     } })

-- Default springs
hl.curve("easy",           { type = "spring", mass = 1, stiffness = 71.2633, dampening = 15.8273644 })

hl.animation({ leaf = "global",        enabled = true,  speed = 10,   bezier = "default" })
hl.animation({ leaf = "border",        enabled = true,  speed = 5.39, bezier = "easeOutQuint" })
hl.animation({ leaf = "windows",       enabled = true,  speed = 4.79, spring = "easy" })
hl.animation({ leaf = "windowsIn",     enabled = true,  speed = 4.1,  spring = "easy",         style = "popin 87%" })
hl.animation({ leaf = "windowsOut",    enabled = true,  speed = 1.49, bezier = "linear",       style = "popin 87%" })
hl.animation({ leaf = "fadeIn",        enabled = true,  speed = 1.73, bezier = "almostLinear" })
hl.animation({ leaf = "fadeOut",       enabled = true,  speed = 1.46, bezier = "almostLinear" })
hl.animation({ leaf = "fade",          enabled = true,  speed = 3.03, bezier = "quick" })
hl.animation({ leaf = "layers",        enabled = true,  speed = 3.81, bezier = "easeOutQuint" })
hl.animation({ leaf = "layersIn",      enabled = true,  speed = 4,    bezier = "easeOutQuint", style = "fade" })
hl.animation({ leaf = "layersOut",     enabled = true,  speed = 1.5,  bezier = "linear",       style = "fade" })
hl.animation({ leaf = "fadeLayersIn",  enabled = true,  speed = 1.79, bezier = "almostLinear" })
hl.animation({ leaf = "fadeLayersOut", enabled = true,  speed = 1.39, bezier = "almostLinear" })
hl.animation({ leaf = "workspaces",    enabled = true,  speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesIn",  enabled = true,  speed = 1.21, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesOut", enabled = true,  speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "zoomFactor",    enabled = true,  speed = 7,    bezier = "quick" })

-- Ref https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/
-- "Smart gaps" / "No gaps when only"
-- uncomment all if you wish to use that.
-- hl.workspace_rule({ workspace = "w[tv1]", gaps_out = 0, gaps_in = 0 })
-- hl.workspace_rule({ workspace = "f[1]",   gaps_out = 0, gaps_in = 0 })

-- Réserve les workspaces 1-5 à l'écran du laptop (eDP-1). Sans ça, le premier
-- écran externe branché récupère automatiquement un des numéros bas (ex: 2),
-- et SUPER+2 depuis le laptop bascule sur cet écran au lieu d'ouvrir un
-- workspace 2 sur le laptop lui-même. Les workspaces 6-10 restent libres,
-- donc naturellement disponibles pour n'importe quel écran externe branché.
for i = 1, 5 do
    hl.workspace_rule({ workspace = tostring(i), monitor = "eDP-1" })
end
-- hl.window_rule({
--     name  = "no-gaps-wtv1",
--     match = { float = false, workspace = "w[tv1]" },
--     border_size = 0,
--     rounding    = 0,
-- })
-- hl.window_rule({
--     name  = "no-gaps-f1",
--     match = { float = false, workspace = "f[1]" },
--     border_size = 0,
--     rounding    = 0,
-- })

-- See https://wiki.hypr.land/Configuring/Layouts/Dwindle-Layout/ for more
hl.config({
    dwindle = {
        preserve_split = true, -- You probably want this
    },
})

-- See https://wiki.hypr.land/Configuring/Layouts/Master-Layout/ for more
hl.config({
    master = {
        new_status = "master",
    },
})

-- See https://wiki.hypr.land/Configuring/Layouts/Scrolling-Layout/ for more
hl.config({
    scrolling = {
        fullscreen_on_one_column = true,
    },
})

----------------
----  MISC  ----
----------------

hl.config({
    misc = {
        force_default_wallpaper = -1,    -- Set to 0 or 1 to disable the anime mascot wallpapers
        disable_hyprland_logo   = false, -- If true disables the random hyprland logo / anime girl background. :(
    },
})


---------------
---- INPUT ----
---------------

hl.config({
    input = {
        kb_layout  = "us",
        kb_variant = "altgr-intl",
        kb_model   = "",
        kb_options = "caps:menu", -- Caps Lock -> touche Menu (voir le bind SUPER + Menu plus bas)
        kb_rules   = "",

        follow_mouse = 1,

        sensitivity = 0, -- -1.0 - 1.0, 0 means no modification.

        touchpad = {
            natural_scroll         = true,  -- le contenu suit le sens des doigts
            tap_to_click           = true,  -- taper = cliquer, sans appuyer physiquement
            tap_and_drag           = true,  -- taper puis glisser = drag (sans maintenir le bouton)
            clickfinger_behavior   = true,  -- 1 doigt = clic gauche, 2 doigts = clic droit, 3 = clic milieu
            disable_while_typing   = true,  -- évite les clics accidentels en tapant au clavier
            scroll_factor          = 1.0,   -- vitesse de défilement (1.0 = normal, augmente/diminue si besoin)
        },
    },
})

hl.gesture({
    fingers = 3,
    direction = "horizontal",
    action = "workspace"
})

-- Example per-device config
-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Devices/ for more
hl.device({
    name        = "epic-mouse-v1",
    sensitivity = -0.5,
})

-- Souris Lenovo (jugée trop sensible) : -1.0 (mini) à 1.0 (maxi), 0 = pas de changement
hl.device({
    name        = "lenovo-lenovo-usb-a-pro-unified-pairing-receiver-1",
    sensitivity = -0.4,
})


---------------------
---- KEYBINDINGS ----
---------------------

local mainMod = "SUPER" -- Sets "Windows" key as main modifier

-- Example binds, see https://wiki.hypr.land/Configuring/Basics/Binds/ for more
-- Nouveau terminal dans le dossier courant du terminal actif (voir le
-- script pour le pourquoi), pas toujours $HOME.
hl.bind(mainMod .. " + Q", hl.dsp.exec_cmd("python3 $HOME/.config/hypr/scripts/smart-terminal.py"))
local closeWindowBind = hl.bind(mainMod .. " + C", hl.dsp.window.close())
-- closeWindowBind:set_enabled(false)
hl.bind(mainMod .. " + M", hl.dsp.exec_cmd("$HOME/.config/hypr/scripts/wlogout.sh"))
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd(fileManager))
hl.bind(mainMod .. " + V", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + R", hl.dsp.exec_cmd(menu))
hl.bind(mainMod .. " + P", hl.dsp.window.pseudo())
hl.bind(mainMod .. " + J", hl.dsp.layout("togglesplit"))    -- dwindle only
hl.bind(mainMod .. " + L", hl.dsp.exec_cmd("hyprlock"))

-- Caps Lock ne fait plus Echap (voir input.kb_options) : ALT + Caps Lock
-- (remappée en "Menu") déplace le focus clavier vers l'autre écran. Deux
-- essais précédents en tap simple ont échoué : binder "Caps_Lock"
-- directement ne marche pas (touche "lock" au sens XKB, traitée
-- différemment des touches normales), et même une fois remappée en
-- "Menu" (un vrai ONE_LEVEL comme Escape, LED de verrouillage confirmée
-- éteinte), Hyprland ne déclenchait quand même pas le bind en tap seul —
-- limite propre à ce fork. "HYPER" en modificateur de bind échoue aussi
-- ("Unknown keysym", seuls SUPER/SHIFT/CTRL/ALT sont reconnus) :
-- modificateur classique + touche normale est ce qui reste.
hl.bind("ALT + Menu", hl.dsp.exec_cmd("$HOME/.config/hypr/scripts/focus-other-monitor.sh"))
hl.bind(mainMod .. " + CTRL + D", hl.dsp.exec_cmd("python3 $HOME/.config/hypr/scripts/arrange-monitor.py"))

-- Alt+Tab : cycle entre les fenêtres du bureau actuel (jamais entre workspaces)
hl.bind("ALT + Tab", hl.dsp.window.cycle_next())
hl.bind("ALT + Tab", hl.dsp.window.bring_to_top())

-- Pense-bête des raccourcis clavier (liste statique, voir le script pour le pourquoi)
hl.bind(mainMod .. " + slash", hl.dsp.exec_cmd("$HOME/.config/hypr/scripts/show-keybinds.sh"))

-- Sélecteur de couleur d'accent (change theme/palette.sh + régénère)
hl.bind(mainMod .. " + T", hl.dsp.exec_cmd("$HOME/.config/hypr/scripts/theme-picker.sh"))

-- Température de couleur écran (filtre lumière bleue, hyprsunset)
hl.bind(mainMod .. " + bracketleft",  hl.dsp.exec_cmd("$HOME/.config/hypr/scripts/adjust-temperature.sh warmer"), { repeating = true })
hl.bind(mainMod .. " + bracketright", hl.dsp.exec_cmd("$HOME/.config/hypr/scripts/adjust-temperature.sh cooler"), { repeating = true })

-- Menu wifi (networkmanager-dmenu, thémé Rofi)
hl.bind(mainMod .. " + W", hl.dsp.exec_cmd("networkmanager_dmenu"))

-- Touche Copilot (envoie SUPER+SHIFT+XF86Assistant, keycode 201 non résolu
-- par son nom symbolique donc ciblé par code physique) : ouvre le panneau swaync
hl.bind(mainMod .. " + SHIFT + XF86Assistant", hl.dsp.exec_cmd("swaync-client -t -sw"))
hl.bind(mainMod .. " + N", hl.dsp.exec_cmd("swaync-client -t -sw"))

-- Captures d'écran (grim + slurp), annotation via swappy
hl.bind("Print",          hl.dsp.exec_cmd("grim -g \"$(slurp)\" - | swappy -f -"))
hl.bind("SHIFT + Print",  hl.dsp.exec_cmd("grim - | swappy -f -"))

-- Move focus with mainMod + arrow keys
hl.bind(mainMod .. " + left",  hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + up",    hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + down",  hl.dsp.focus({ direction = "down" }))

-- Swap the active window's position with its neighbor, mainMod + SHIFT + arrow keys
hl.bind(mainMod .. " + SHIFT + left",  hl.dsp.window.swap({ direction = "l" }))
hl.bind(mainMod .. " + SHIFT + right", hl.dsp.window.swap({ direction = "r" }))
hl.bind(mainMod .. " + SHIFT + up",    hl.dsp.window.swap({ direction = "u" }))
hl.bind(mainMod .. " + SHIFT + down",  hl.dsp.window.swap({ direction = "d" }))

-- Resize the active window with mainMod + CTRL + arrow keys (hold to keep resizing)
hl.bind(mainMod .. " + CTRL + left",  hl.dsp.window.resize({ x = -50, y = 0, relative = true }), { repeating = true })
hl.bind(mainMod .. " + CTRL + right", hl.dsp.window.resize({ x = 50,  y = 0, relative = true }), { repeating = true })
hl.bind(mainMod .. " + CTRL + up",    hl.dsp.window.resize({ x = 0, y = -50, relative = true }), { repeating = true })
hl.bind(mainMod .. " + CTRL + down",  hl.dsp.window.resize({ x = 0, y = 50,  relative = true }), { repeating = true })

-- Switch workspaces with mainMod + [0-9]
-- Move active window to a workspace with mainMod + SHIFT + [0-9]
for i = 1, 10 do
    local key = i % 10 -- 10 maps to key 0
    hl.bind(mainMod .. " + " .. key,             hl.dsp.focus({ workspace = i}))
    hl.bind(mainMod .. " + SHIFT + " .. key,     hl.dsp.window.move({ workspace = i }))
end

-- Example special workspace (scratchpad)
hl.bind(mainMod .. " + S",         hl.dsp.workspace.toggle_special("magic"))
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.window.move({ workspace = "special:magic" }))

-- Scroll through existing workspaces with mainMod + scroll
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up",   hl.dsp.focus({ workspace = "e-1" }))

-- Move/resize windows with mainMod + LMB/RMB and dragging
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(),   { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Laptop multimedia keys for volume and LCD brightness
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"),      { locked = true, repeating = true })
hl.bind("XF86AudioMute",        hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"),     { locked = true, repeating = true })
hl.bind("XF86AudioMicMute",     hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"),   { locked = true, repeating = true })
hl.bind("XF86MonBrightnessUp",  hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+"),                  { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown",hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-"),                  { locked = true, repeating = true })

-- Requires playerctl
hl.bind("XF86AudioNext",  hl.dsp.exec_cmd("playerctl next"),       { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay",  hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev",  hl.dsp.exec_cmd("playerctl previous"),   { locked = true })


--------------------------------
---- WINDOWS AND WORKSPACES ----
--------------------------------

-- See https://wiki.hypr.land/Configuring/Basics/Window-Rules/
-- and https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/

-- Example window rules that are useful

local suppressMaximizeRule = hl.window_rule({
    -- Ignore maximize requests from all apps. You'll probably like this.
    name  = "suppress-maximize-events",
    match = { class = ".*" },

    suppress_event = "maximize",
})
-- suppressMaximizeRule:set_enabled(false)

hl.window_rule({
    -- Fix some dragging issues with XWayland
    name  = "fix-xwayland-drags",
    match = {
        class      = "^$",
        title      = "^$",
        xwayland   = true,
        float      = true,
        fullscreen = false,
        pin        = false,
    },

    no_focus = true,
})

-- Layer rules also return a handle.
-- local overlayLayerRule = hl.layer_rule({
--     name  = "no-anim-overlay",
--     match = { namespace = "^my-overlay$" },
--     no_anim = true,
-- })
-- overlayLayerRule:set_enabled(false)

-- Hyprland-run windowrule
hl.window_rule({
    name  = "move-hyprland-run",
    match = { class = "hyprland-run" },

    move  = "20 monitor_h-120",
    float = true,
})

-- nm-connection-editor : bugs de clic en mode tuilé (GTK3 mal synchro avec
-- le redimensionnement live), on le force en flottant.
hl.window_rule({
    name    = "float-nm-connection-editor",
    match   = { class = "nm-connection-editor" },

    float   = true,
    center  = true,
})
