general {
    hide_cursor = true
}

background {
    monitor =
    color = rgba(fbf1c7ff)
}

input-field {
    monitor =
    size = 250, 60
    rounding = 3
    outline_thickness = 4
    dots_size = 0.25
    dots_spacing = 0.3
    dots_rounding = 1
    outer_color = rgba(e91e8cff)
    inner_color = rgba(ebdbb2ff)
    font_color = rgba(3c3836ff)
    fade_on_empty = false
    placeholder_text = <span> </span>
    position = 0, -20
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +'%H:%M')"
    color = rgba(3c3836ff)
    font_size = 64
    font_family = JetBrainsMono Nerd Font Mono
    position = 0, 150
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] echo "$(date +'%A %d %B')"
    color = rgba(504945ff)
    font_size = 20
    font_family = JetBrainsMono Nerd Font Mono
    position = 0, 90
    halign = center
    valign = center
}
